# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

[fr]
  languageCode = "fr"
  contentDir = "content/fr"
  [fr.params]
    email = "remi_theriault à uqar.ca"
    phone = "418 723-1986, extension 1110"
    address = {street = "207A rue Notre-Dame Est", city = "Rimouski", region = "Québec", postcode = "G5L 2A4", country = "Canada", country_code = "CA"}
    directions = "Bureau U-1053 (1er étage), pavillon U. Entrez par l'accès côté rue Notre-Dame, tournez immédiatement à gauche, puis encore à gauche; mon bureau se trouvera sur votre droite."

# Uncomment the lines below to configure your website in a second language.
#[zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
