[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy-Report-Only = '''
      default-src 'none';
      form-action 'none';
      frame-ancestors 'none';
      report-uri https://remitheriault.report-uri.com/r/d/csp/wizard'''

[[redirects]]
  from = "/cv"
  to = "/cv.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/rempsyc"
  to = "https://rempsyc.remi-theriault.com"
  status = 301
  force = true

[[redirects]]
  from = "/blog_table.html"
  to = "https://rempsyc.remi-theriault.com/articles/table"
  status = 301
  force = true

[[redirects]]
  from = "/blog_violin.html"
  to = "https://rempsyc.remi-theriault.com/articles/violin"
  status = 301
  force = true

[[redirects]]
  from = "/blog_scatter.html"
  to = "https://rempsyc.remi-theriault.com/articles/scatter"
  status = 301
  force = true

[[redirects]]
  from = "/blog_circles.html"
  to = "https://rempsyc.remi-theriault.com/articles/circles"
  status = 301
  force = true

[[redirects]]
  from = "/blog_randomize.html"
  to = "https://rempsyc.remi-theriault.com/articles/randomize"
  status = 301
  force = true

[[redirects]]
  from = "/blog_assumptions.html"
  to = "https://rempsyc.remi-theriault.com/articles/assumptions"
  status = 301
  force = true

[[redirects]]
  from = "/blog_moderation.html"
  to = "https://rempsyc.remi-theriault.com/articles/moderation"
  status = 301
  force = true

[[redirects]]
  from = "/blog_t-test.html"
  to = "https://rempsyc.remi-theriault.com/articles/t-test"
  status = 301
  force = true

[[redirects]]
  from = "/blog_contrasts.html"
  to = "https://rempsyc.remi-theriault.com/articles/contrasts"
  status = 301
  force = true




[[redirects]]
  from = "/blog_table"
  to = "https://rempsyc.remi-theriault.com/articles/table"
  status = 301
  force = true

[[redirects]]
  from = "/blog_violin"
  to = "https://rempsyc.remi-theriault.com/articles/violin"
  status = 301
  force = true

[[redirects]]
  from = "/blog_scatter"
  to = "https://rempsyc.remi-theriault.com/articles/scatter"
  status = 301
  force = true

[[redirects]]
  from = "/blog_circles"
  to = "https://rempsyc.remi-theriault.com/articles/circles"
  status = 301
  force = true

[[redirects]]
  from = "/blog_randomize"
  to = "https://rempsyc.remi-theriault.com/articles/randomize"
  status = 301
  force = true

[[redirects]]
  from = "/blog_assumptions"
  to = "https://rempsyc.remi-theriault.com/articles/assumptions"
  status = 301
  force = true

[[redirects]]
  from = "/blog_moderation"
  to = "https://rempsyc.remi-theriault.com/articles/moderation"
  status = 301
  force = true

[[redirects]]
  from = "/blog_t-test"
  to = "https://rempsyc.remi-theriault.com/articles/t-test"
  status = 301
  force = true

[[redirects]]
  from = "/blog_contrasts"
  to = "https://rempsyc.remi-theriault.com/articles/contrasts"
  status = 301
  force = true




[[redirects]]
  from = "/Theriault_IPPA_2019.pdf"
  to = "/posters/Theriault_IPPA_2019.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_Mind&Life_2019.pdf"
  to = "/posters/Theriault_Mind&Life_2019.pdf"
  status = 301
  force = false



[[redirects]]
  from = "/Th%C3%A9riault_2019.pdf"
  to = "/papers/Theriault_2019.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Th%C3%A9riault_et_al_2021.pdf"
  to = "/papers/Theriault_et_al_2021.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_et_al_2022.pdf"
  to = "/papers/Theriault_et_al_2022.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Lifshitz_et_al_2017.pdf"
  to = "/papers/Lifshitz_et_al_2017.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Krol_et_al_2020.pdf"
  to = "/papers/Krol_et_al_2020.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Krol_et_al_2020_SOM.pdf"
  to = "/papers/Krol_et_al_2020_SOM.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_&_Raz_2018.pdf"
  to = "/papers/Theriault_&_Raz_2018.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_&_Raz_2018_SOM.pdf"
  to = "/papers/Theriault_&_Raz_2018_SOM.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_et_al_2021.pdf"
  to = "/papers/Theriault_et_al_2021.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_et_al_2022_SOM.pdf"
  to = "/papers/Theriault_et_al_2022_SOM.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_et_al_2021_SOM.pdf"
  to = "/papers/Theriault_et_al_2021_SOM.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_&_Raz_2018_SOM.pdf"
  to = "/papers/Theriault_&_Raz_2018_SOM.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/papers/Miglianico_et_al_2022.pdf"
  to = "/papers/Miglianico_et_al_2024.pdf"
  status = 301
  force = false


[[redirects]]
  from = "/rempsyc_manual.pdf"
  to = "https://cran.r-project.org/web/packages/rempsyc/rempsyc.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/en/publication/2022-lavaanextra/"
  to = "/en/publication/2023-lavaanextra/"
  status = 301
  force = false

[[redirects]]
  from = "/fr/publication/2022-lavaanextra/"
  to = "/fr/publication/2023-lavaanextra/"
  status = 301
  force = false

[[redirects]]
  from = "/en/publication/2022-rempsyc/"
  to = "/en/publication/2023-rempsyc/"
  status = 301
  force = false

[[redirects]]
  from = "/fr/publication/2022-rempsyc/"
  to = "/fr/publication/2023-rempsyc/"
  status = 301
  force = false

[[redirects]]
  from = "/dashboards/busara/"
  to = "/dashboards/missing_majority/"
  status = 301
  force = false


[[redirects]]
  from = "/publication/2022-pf/"
  to = "/publication/2024-pf/"
  status = 301
  force = false

[[redirects]]
  from = "/fr/publication/2022-pf/"
  to = "/fr/publication/2024-pf/"
  status = 301
  force = false
