"""Generate shared WebP thumbnails without requiring WebP support in Hugo.

Run with Python and Pillow after adding/changing portfolio featured images.
Originals and existing derivative URLs are never removed. Hugo falls back to
its own JPEG/PNG thumbnails if a new source has not been processed yet.
"""

from hashlib import sha256
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "static/media/portfolio"
MANIFEST = ROOT / "data/portfolio_images.toml"
SECTIONS = ("project-blog", "project-media", "project-news", "project-tutorials")


def main():
    sources = {}
    for language in ("en", "fr"):
        for section in SECTIONS:
            for path in sorted((ROOT / "content" / language / section).rglob("*")):
                if "featured" not in path.name or path.suffix.lower() not in (".jpg", ".jpeg", ".png"):
                    continue
                digest = sha256(path.read_bytes()).hexdigest()
                entry = sources.setdefault(digest, {"path": path, "lossless": False})
                # Protect fine text, charts, and logos. Photos use high-quality WebP.
                with Image.open(path) as original:
                    entry["lossless"] |= section == "project-tutorials" or (section == "project-news" and original.format == "PNG")

    OUTPUT.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by scripts/optimize_portfolio_images.py; do not edit.", ""]
    total = 0
    generated = set()
    for digest, entry in sorted(sources.items()):
        with Image.open(entry["path"]) as original:
            has_alpha = "A" in original.getbands() or "transparency" in original.info
            image = ImageOps.exif_transpose(original).convert("RGBA" if has_alpha else "RGB")
            widths = sorted({min(320, image.width), min(550, image.width)})
            recipe = "lossless" if entry["lossless"] else "q88"
            lines.append(f'[images."{digest}"]')
            for width in widths:
                height = max(1, round(image.height * width / image.width))
                resized = image.resize((width, height), Image.Resampling.LANCZOS)
                buffer = BytesIO()
                resized.save(buffer, "WEBP", lossless=entry["lossless"], quality=88, method=6)
                data = buffer.getvalue()
                # Hash the encoded bytes too: encoder changes cannot leave stale CDN content.
                filename = f"{digest[:16]}-{width}-{recipe}-{sha256(data).hexdigest()[:12]}.webp"
                destination = OUTPUT / filename
                generated.add(destination)
                if not destination.exists() or destination.read_bytes() != data:
                    destination.write_bytes(data)
                total += len(data)
                lines.extend([
                    f'[[images."{digest}".variants]]',
                    f'url = "media/portfolio/{filename}"',
                    f"width = {width}",
                    f"height = {height}",
                ])
            lines.append("")
    MANIFEST.write_text("\n".join(lines), encoding="utf-8")
    # This dedicated directory contains only generated files, never originals.
    for stale in OUTPUT.glob("*.webp"):
        if stale not in generated and stale.resolve().parent == OUTPUT.resolve():
            stale.unlink()
    print(f"Generated shared WebP variants for {len(sources)} unique sources: {total:,} bytes.")


if __name__ == "__main__":
    main()
